from __future__ import annotations

import copy
import json
from pathlib import Path

from build_round1_scene import box, grid, label, node, sty


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "figure1_concept_threat.round2.scene.json"


def main():
    inventory_scene = json.loads((ROOT / "figure1_concept_threat.scene.json").read_text(encoding="utf-8"))
    metadata = copy.deepcopy(inventory_scene["metadata"])
    metadata.update({
        "created_by": "codex.visiomaster.fresh_round2",
        "replica_stage": "detail_polish",
        "prior_scene_policy": "reuse_source_inventory_and_arrow_plan_only; reauthor_all_visible_nodes",
        "notes": [
            "Fresh full-scene reauthoring from source inventory and round-one findings.",
            "Human, subframe, and camera zones use independent vertical bands.",
            "Every long English label uses dedicated rows and explicit text margins.",
            "Office geometry is reauthored as simplified editable editorial line art.",
        ],
    })
    metadata["region_plan"] = [
        {"id":"global_layout","crop_type":"global","source_bbox_px":[0,0,1536,1024],
         "target_bbox":[0,0,1536,1024],"review_focus":"global layout and two-panel balance"},
        {"id":"physical_input","crop_type":"input","source_bbox_px":[0,0,730,1024],
         "target_bbox":[20,20,710,1000],"container_id":"physical_scene",
         "review_focus":"physical eavesdropping scene and labels"},
        {"id":"subframe_core","crop_type":"core","source_bbox_px":[760,350,1500,650],
         "target_bbox":[750,370,1510,690],"container_id":"subframe_region",
         "review_focus":"four subframes time axis and selected frame"},
        {"id":"human_output","crop_type":"output","source_bbox_px":[900,60,1510,350],
         "target_bbox":[830,80,1510,440],"container_id":"human_region",
         "review_focus":"right output human integration"},
        {"id":"camera_output","crop_type":"output","source_bbox_px":[870,610,1536,940],
         "target_bbox":[850,650,1520,1000],"container_id":"camera_region",
         "review_focus":"right output camera sampling"},
        {"id":"arrow_dense","crop_type":"arrow_dense","source_bbox_px":[760,120,1536,900],
         "target_bbox":[760,120,1520,930],"review_focus":"human fan-in and camera selection topology"},
        {"id":"small_text","crop_type":"small_text","source_bbox_px":[20,0,1536,960],
         "target_bbox":[20,0,1520,960],"review_focus":"small text display words and captions"},
    ]

    navy = "#17365D"
    green = "#177A36"
    red = "#D94722"
    pale_blue = "#DFF3FA"

    nodes = [
        node("page_background", "page_background", 0, 0, 1536, 1024, z=-100),
        node("physical_scene", "audit_region", 20, 20, 690, 980, z=-10,
             label="Physical visual eavesdropping", source_bbox_px=[0,0,730,1024],
             source_aspect_ratio=0.713, style=sty(fill="none", line="none")),
        node("subframe_region", "audit_region", 750, 370, 760, 320, z=-10,
             label="Rapid complementary subframes", source_bbox_px=[760,350,1500,650],
             source_aspect_ratio=2.467, style=sty(fill="none", line="none")),
        node("human_region", "audit_region", 830, 80, 680, 360, z=-10,
             label="Human integration", source_bbox_px=[900,60,1510,350],
             source_aspect_ratio=2.103, style=sty(fill="none", line="none")),
        node("camera_region", "audit_region", 850, 650, 670, 350, z=-10,
             label="Camera sampling", source_bbox_px=[870,610,1536,940],
             source_aspect_ratio=2.018, style=sty(fill="none", line="none")),
        node("panel_divider", "polygon_node", 720, 20, 4, 980, z=5,
             points=[[0,0],[1,0],[1,1],[0,1]],
             style=sty(fill=navy, line=navy, line_weight_pt=0.6)),

        label("panel_a_title", 30, 22, 675, 62, "(a)  Physical visual eavesdropping",
              "physical_scene", size=6.5, weight="bold", role="panel_title", align=0),
        label("authorized_line1", 25, 230, 245, 60, "Authorized", "physical_scene",
              size=6.5, weight="bold"),
        label("authorized_line2", 25, 278, 245, 60, "user", "physical_scene",
              size=6.7, weight="bold"),
        label("sensitive_line1", 270, 175, 230, 60, "Sensitive", "physical_scene",
              size=6.7, weight="bold"),
        label("sensitive_line2", 270, 222, 230, 60, "display", "physical_scene",
              size=6.7, weight="bold"),
        label("phone_line1", 440, 820, 260, 60, "Smartphone", "physical_scene",
              size=6.5, color=red, weight="bold"),
        label("phone_line2", 440, 868, 260, 60, "camera", "physical_scene",
              size=6.6, color=red, weight="bold"),

        box("chair_back", 48, 505, 130, 300, "physical_scene", rounded=True, weight=1.15,
            allow_overlap=True),
        box("chair_seat", 105, 730, 190, 55, "physical_scene", rounded=True, weight=1.15,
            allow_overlap=True),
        node("chair_support", "polygon_node", 105, 782, 150, 165, container="physical_scene", z=8,
             allow_overlap=True, points=[[0.42,0],[0.58,0],[0.58,0.60],[1,1],[0.5,0.72],[0,1],[0.42,0.60]],
             style=sty(fill="none", line=navy, line_weight_pt=1.05)),
        node("user_torso", "polygon_node", 92, 455, 235, 285, container="physical_scene", z=11,
             allow_overlap=True,
             points=[[0.30,0],[0.62,0.08],[0.84,0.35],[1,0.73],[0.76,1],[0.18,0.88],[0,0.38]],
             style=sty(fill="#F7FAFC", line=navy, line_weight_pt=1.2)),
        node("user_head", "ellipse_node", 150, 335, 92, 116, container="physical_scene", z=12,
             allow_overlap=True, style=sty(fill="#FFFFFF", line=navy, line_weight_pt=1.2,
                                           font_family="Arial", font_size_pt=7.0)),
        node("user_hair", "polygon_node", 137, 320, 108, 84, container="physical_scene", z=13,
             allow_overlap=True,
             points=[[0.05,0.6],[0.20,0.18],[0.55,0],[0.90,0.18],[1,0.48],[0.72,0.55],[0.62,1],[0.35,0.8]],
             style=sty(fill="#3B4F75", line=navy, line_weight_pt=1.0)),
        node("user_arm", "polygon_node", 225, 505, 180, 105, container="physical_scene", z=13,
             allow_overlap=True,
             points=[[0,0.10],[0.22,0],[0.62,0.53],[1,0.53],[1,0.82],[0.55,0.90],[0.18,0.50]],
             style=sty(fill="#FFFFFF", line=navy, line_weight_pt=1.1)),
        box("desk_top", 42, 580, 545, 44, "physical_scene", fill="#FFFFFF", weight=1.2,
            allow_overlap=True),
        box("desk_cabinet", 430, 624, 155, 260, "physical_scene", fill="#FFFFFF", weight=1.2),
        node("desk_leg", "polygon_node", 65, 624, 26, 230, container="physical_scene", z=8,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill="#FFFFFF", line=navy, line_weight_pt=1.0)),
        box("keyboard", 275, 540, 150, 34, "physical_scene", fill="#FFFFFF", weight=1.0,
            allow_overlap=True),
        box("bookshelf", 560, 235, 105, 240, "physical_scene", fill="#FFFFFF", weight=1.0),
        node("bookshelf_lines", "grid_matrix", 566, 242, 93, 225, container="physical_scene", z=9,
             rows=3, cols=1, colored_cells=[], style=sty(cell_fill="#FFFFFF", grid_line="#17365D",
                                                         grid_line_weight_pt=0.55)),

        box("sensitive_display", 245, 280, 250, 210, "physical_scene", fill="#FFFFFF",
            weight=1.35, rounded=True),
        box("display_screen", 260, 300, 220, 150, "physical_scene", fill=pale_blue, weight=1.0),
        label("display_private", 270, 318, 200, 60, "PRIVATE", "physical_scene",
              size=6.8, weight="bold", role="node_text"),
        label("display_data", 270, 385, 200, 60, "DATA", "physical_scene",
              size=6.8, weight="bold", role="node_text"),
        box("display_stand", 350, 490, 40, 45, "physical_scene", fill="#FFFFFF", weight=1.0),
        node("display_base", "polygon_node", 310, 532, 120, 16, container="physical_scene", z=11,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill="#FFFFFF", line=navy, line_weight_pt=1.0)),

        node("phone_hand", "ellipse_node", 585, 635, 105, 185, container="physical_scene", z=9,
             allow_overlap=True, style=sty(fill="#FFF7F2", line=red, line_weight_pt=1.0,
                                           font_family="Arial", font_size_pt=7.0)),
        box("smartphone", 608, 520, 72, 155, "physical_scene", fill="#FFFFFF", line=red,
            weight=1.35, rounded=True, z=14, allow_overlap=True),
        box("phone_screen", 618, 540, 52, 108, "physical_scene", fill="#FFF6F2", line=red,
            weight=0.8, z=15),
        node("phone_lens", "ellipse_node", 620, 527, 11, 11, container="physical_scene", z=16,
             allow_overlap=True, style=sty(fill="#FFFFFF", line=red, line_weight_pt=0.8,
                                           font_family="Arial", font_size_pt=7.0)),

        label("panel_b_title", 760, 22, 740, 62, "(b)  Asymmetric perception",
              "human_region", size=7.8, weight="bold", role="panel_title", align=1),
        label("human_eye_label", 875, 90, 260, 58, "Human eye", "human_region",
              size=6.8, color=green, weight="bold"),
        node("human_eye", "ellipse_node", 920, 145, 165, 92, container="human_region", z=13,
             style=sty(fill="#FFFFFF", line=green, line_weight_pt=1.35,
                       font_family="Arial", font_size_pt=7.0)),
        node("human_pupil", "ellipse_node", 982, 162, 42, 56, container="human_region", z=14,
             allow_overlap=True, style=sty(fill="#179447", line=green, line_weight_pt=1.0,
                                           font_family="Arial", font_size_pt=7.0)),
        label("integration_line1", 1260, 300, 230, 36, "Temporal", "human_region",
              size=6.5, color=green, weight="bold"),
        label("integration_line2", 1260, 336, 230, 36, "integration", "human_region",
              size=6.5, color=green, weight="bold"),
        label("integration_time", 1260, 372, 230, 36, "≈ 50 ms", "human_region",
              size=6.7, color=green, weight="bold"),
        box("readable_display", 1270, 130, 230, 160, "human_region", fill="#FFFFFF",
            line=navy, weight=1.35, rounded=True),
        box("readable_screen", 1285, 148, 200, 105, "human_region", fill=pale_blue, line=navy, weight=0.9),
        label("readable_private", 1290, 155, 190, 48, "PRIVATE", "human_region",
              size=6.8, weight="bold", role="node_text"),
        label("readable_data", 1290, 205, 190, 48, "DATA", "human_region",
              size=6.8, weight="bold", role="node_text"),
        box("readable_stand", 1378, 290, 30, 27, "human_region", fill="#FFFFFF", weight=0.9),
        node("readable_base", "polygon_node", 1355, 315, 78, 12, container="human_region", z=11,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill=navy, line=navy, line_weight_pt=0.5)),
        label("readable_label", 1235, 82, 265, 48, "Readable", "human_region",
              size=6.5, color=green, weight="bold", role="output_label"),

        label("fast_label", 750, 310, 110, 42, "Fast", "subframe_region",
              size=6.5, weight="bold"),
        label("time_label", 750, 347, 110, 42, "time", "subframe_region",
              size=6.5, weight="bold"),
        box("subframe_1", 785, 465, 120, 100, "subframe_region", fill="#FFFFFF", weight=1.1, rounded=True),
        grid("subframe_grid_1", 795, 475, 100, 72, [(0,0),(0,2),(2,4),(3,1)], "subframe_region"),
        node("subframe_1_base", "polygon_node", 820, 565, 50, 12, container="subframe_region", z=12,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill=navy,line=navy,line_weight_pt=0.5)),
        box("subframe_2", 935, 465, 120, 100, "subframe_region", fill="#FFFFFF", weight=1.1, rounded=True),
        grid("subframe_grid_2", 945, 475, 100, 72, [(0,1),(0,3),(0,4),(2,2)], "subframe_region"),
        node("subframe_2_base", "polygon_node", 970, 565, 50, 12, container="subframe_region", z=12,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill=navy,line=navy,line_weight_pt=0.5)),
        box("subframe_3", 1085, 465, 120, 100, "subframe_region", fill="#FFFFFF", weight=1.1, rounded=True),
        grid("subframe_grid_3", 1095, 475, 100, 72, [(1,0),(2,1),(3,2),(2,3),(1,4)], "subframe_region"),
        node("subframe_3_base", "polygon_node", 1120, 565, 50, 12, container="subframe_region", z=12,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill=navy,line=navy,line_weight_pt=0.5)),
        box("subframe_4", 1235, 465, 120, 100, "subframe_region", fill="#FFFFFF", weight=1.1, rounded=True),
        grid("subframe_grid_4", 1245, 475, 100, 72, [(0,2),(0,3),(1,3),(2,0),(3,3)], "subframe_region"),
        node("subframe_4_base", "polygon_node", 1270, 565, 50, 12, container="subframe_region", z=12,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill=navy,line=navy,line_weight_pt=0.5)),
        node("selection_left", "bracket", 925, 450, 16, 135, container="subframe_region", z=18,
             orientation="left", shape="square", tick_positions=[0,1],
             style=sty(line=red, line_weight_pt=1.2)),
        node("selection_right", "bracket", 1050, 450, 16, 135, container="subframe_region", z=18,
             orientation="right", shape="square", tick_positions=[0,1],
             style=sty(line=red, line_weight_pt=1.2)),
        label("subframe_label_1", 1120, 580, 350, 38, "Rapid", "subframe_region",
              size=6.5, weight="bold"),
        label("subframe_label_2", 1120, 615, 350, 38, "complementary", "subframe_region",
              size=6.5, weight="bold"),
        label("subframe_label_3", 1120, 650, 350, 38, "subframes", "subframe_region",
              size=6.5, weight="bold"),

        box("camera_icon", 900, 800, 115, 88, "camera_region", fill="#FFFFFF", line=red,
            weight=1.35, rounded=True),
        node("camera_lens", "ellipse_node", 937, 819, 42, 42, container="camera_region", z=14,
             allow_overlap=True, style=sty(fill="#FFFFFF", line=red, line_weight_pt=1.2,
                                           font_family="Arial", font_size_pt=7.0)),
        node("camera_top", "polygon_node", 928, 786, 34, 16, container="camera_region", z=13,
             allow_overlap=True, points=[[0,0],[1,0],[1,1],[0,1]],
             style=sty(fill="#FFFFFF", line=red, line_weight_pt=1.0)),
        label("camera_label", 850, 905, 180, 48, "Camera", "camera_region",
              size=6.7, color=red, weight="bold"),
        label("sampling_label_1", 1020, 710, 300, 36, "Instantaneous", "camera_region",
              size=6.3, color=red, weight="bold"),
        label("sampling_label_2", 1020, 748, 300, 36, "sampling", "camera_region",
              size=6.3, color=red, weight="bold"),
        box("fragment_display", 1190, 800, 115, 88, "camera_region", fill="#FFFFFF",
            line=navy, weight=1.1, rounded=True),
        grid("fragment_grid", 1200, 810, 95, 60, [(0,0),(3,3)], "camera_region"),
        node("fragment_base", "polygon_node", 1222, 888, 50, 12, container="camera_region", z=12,
             points=[[0,0],[1,0],[1,1],[0,1]], style=sty(fill=navy,line=navy,line_weight_pt=0.5)),
        label("fragment_label_1", 1170, 905, 240, 48, "Unreadable", "camera_region",
              size=6.5, color=red, weight="bold"),
        label("fragment_label_2", 1170, 943, 240, 48, "fragment", "camera_region",
              size=6.5, color=red, weight="bold"),
        node("ocr_failure", "ellipse_node", 1395, 798, 105, 92, text="OCR ×", container="camera_region", z=13,
             style=sty(fill="#FFFFFF", line=red, line_weight_pt=1.25, text_color=navy,
                       source_font_family="Arial", font_family="Arial", font_family_candidates=["Arial","Calibri"],
                       font_role="sans", font_size_pt=6.8, min_font_size_pt=6.5, font_weight="bold",
                       text_fit="single_line", constrain_text_box=True, text_margin_in=0.0)),
    ]

    edges = [
        {"id":"capture_ray_upper","type":"line_segment","arrow_plan_id":"A001",
         "from_point":[480,365],"to_point":[610,545],"route":"straight","allow_diagonal":True,
         "style":{"line":red,"line_weight_pt":1.0,"line_dash":"dash","end_arrow":"none"},"z":30},
        {"id":"capture_ray_lower","type":"line_segment","arrow_plan_id":"A002",
         "from_point":[480,430],"to_point":[610,630],"route":"straight","allow_diagonal":True,
         "style":{"line":red,"line_weight_pt":1.0,"line_dash":"dash","end_arrow":"none"},"z":30},
        {"id":"time_axis","type":"lane_arrow","arrow_plan_id":"A003",
         "from_point":[785,430],"to_point":[1350,430],"route":"horizontal","lane_axis":"horizontal",
         "style":{"line":navy,"line_weight_pt":1.15,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"frame1_to_eye","type":"arrow_connector","arrow_plan_id":"A004",
         "from":"subframe_1:top@0.50","to":"human_eye:bottom@0.15","route":"straight",
         "allow_diagonal":True,"allow_cross_container":True,
         "style":{"line":green,"line_weight_pt":1.2,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"frame2_to_eye","type":"arrow_connector","arrow_plan_id":"A005",
         "from":"subframe_2:top@0.50","to":"human_eye:bottom@0.38","route":"straight",
         "allow_diagonal":True,"allow_cross_container":True,
         "style":{"line":green,"line_weight_pt":1.2,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"frame3_to_eye","type":"arrow_connector","arrow_plan_id":"A006",
         "from":"subframe_3:top@0.50","to":"human_eye:bottom@0.62","route":"straight",
         "allow_diagonal":True,"allow_cross_container":True,
         "style":{"line":green,"line_weight_pt":1.2,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"frame4_to_eye","type":"arrow_connector","arrow_plan_id":"A007",
         "from":"subframe_4:top@0.50","to":"human_eye:bottom@0.85","route":"straight",
         "allow_diagonal":True,"allow_cross_container":True,
         "style":{"line":green,"line_weight_pt":1.2,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"eye_to_readable","type":"lane_arrow","arrow_plan_id":"A008",
         "from":"human_eye:right@0.50","to":"readable_display:left@0.50","route":"horizontal","lane_axis":"horizontal",
         "style":{"line":green,"line_weight_pt":1.25,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"selected_to_camera","type":"lane_arrow","arrow_plan_id":"A009",
         "from":"subframe_2:bottom@0.50","to":"camera_icon:top@0.50","route":"vertical","lane_axis":"vertical",
         "allow_cross_container":True,
         "style":{"line":red,"line_weight_pt":1.25,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"camera_to_fragment","type":"lane_arrow","arrow_plan_id":"A010",
         "from":"camera_icon:right@0.50","to":"fragment_display:left@0.50","route":"horizontal","lane_axis":"horizontal",
         "style":{"line":red,"line_weight_pt":1.25,"end_arrow":"triangle","arrow_size":"small"},"z":25},
        {"id":"fragment_to_ocr","type":"lane_arrow","arrow_plan_id":"A011",
         "from":"fragment_display:right@0.50","to":"ocr_failure:left@0.50","route":"horizontal","lane_axis":"horizontal",
         "style":{"line":red,"line_weight_pt":1.25,"end_arrow":"triangle","arrow_size":"small"},"z":25},
    ]

    scene = {
        "version": "0.1",
        "metadata": metadata,
        "page": {"width":1536,"height":1024,"units":"px","origin":"top-left",
                 "target_width_in":3.5,"background":"#FFFFFF"},
        "nodes": nodes,
        "edges": edges,
        "assets": [],
    }
    OUTPUT.write_text(json.dumps(scene, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
